.drone.yml, .npmrc, Dockerfile, environments/prod.yaml, environments/staging.yaml, next.config.js, src/pages/api/health.ts
[DEVHUB-1383](https://jira.mongodb.org/browse/DEVHUB-1383)
=> [DEVHUB-1383] Create drone pipeline with Kanopy deployments.

src/components/markdown/component-mappings/a/index.tsx, src/components/markdown/component-mappings/a/styles.ts
Scope
- Adds link component for markdown content
=> [DEVHUB-1410]: Markdown Link Component

.drone.yml, Dockerfile, src/lib/cms-content.ts, src/pages/courses/[course].tsx, src/pages/index.tsx
[DEVHUB-1413](https://jira.mongodb.org/browse/DEVHUB-1413)
@justinmckenzie There are 2 new env variables that you'll need after this. I can 0bin them to you.
Right now the data is just being passed into the component, so should be ready to use.
=> [DEVHUB-1413] Get data from Strapi

data/hero.json, data/statistics.json, data/student-resources.json, src/components/course-aside/course-aside.tsx, src/components/course-body/course-body.tsx, src/components/course-header/course-header.tsx, src/components/course-list/course-list.tsx, src/components/course-list/styles.ts, src/components/featured-card/featured-card.tsx, src/components/featured-card/types.ts, src/components/hero/hero.spec.tsx, src/components/hero/hero.tsx, src/components/hero/types.ts, src/components/statistic/styles.ts, src/components/student-resources/student-resources.tsx, src/components/student-resources/types.ts, src/pages/index.tsx, src/styles/home.ts, tsconfig.json
Scope
- Updates static content from the updated Educator's Copy doc
- Extracted static content into separate JSON files for easy updating
- small CSS updates
=> [CHORE]: Update Static Text & Content

.github/workflows/pull-request-checks.yml, .lintstagedrc.js, jest.config.js, src/components/course-body/course-body.spec.tsx, src/components/course-body/types.ts, src/components/course-list/course-list.spec.tsx, src/components/student-resources/student-resources.spec.tsx
[DEVHUB-1387](https://jira.mongodb.org/browse/DEVHUB-1387)
=> [DEVHUB-1387] Add github actions CI tests

package.json, src/components/card/card.tsx, src/components/card/styles.ts, src/components/card/types.ts, src/components/content-preview/content-preview.spec.tsx, src/components/content-preview/content-preview.tsx, src/components/content-preview/styles.ts, src/components/featured-card/styles.ts, src/components/student-resources/student-resources.spec.tsx, src/components/student-resources/styles.ts, src/lib/cms-content.ts, src/pages/index.tsx
Scope
- Wire up components in Home Page with data from Strapi
- Remove old mock data
- Small CSS updates
=> [DEVHUB-1375] & [DEVHUB-1376]: Integrate Home Page Data & Routing Functionality

data/student-resources.json, src/components/featured-card/featured-card.tsx, src/components/featured-card/styles.ts, src/components/student-resources/student-resources.tsx, src/components/student-resources/types.ts
Scope
- Secondary Featured Cards will now be in column layout on Desktop, updates styles to account for that while not breaking the `fullWidth` primary Featured Card
- Update CTA Text for secondary featured cards
=> [CHORE]: Featured Card Style Updates

package.json, src/lib/airtable.ts, src/lib/app-services.ts, src/lib/logger.ts, src/lib/rate-limit.ts, src/lib/utils.ts, src/pages/api/registration.ts, src/pages/api/revalidate.ts, yarn.lock
[DEVHUB-1388](https://jira.mongodb.org/browse/DEVHUB-1388)
Taking inspiration from the DevCenter implementation and using Pino. Just logging stuff related to the API endpoints for now, but can expand this to build and browser stuff later.
=> DEVHUB-1388] Add logging to server stuff

data/student-resources.json, src/components/form/form.spec.tsx, src/components/form/form.tsx, src/components/form/styles.ts, src/components/form/types.ts, src/lib/app-services.ts, src/pages/_app.tsx
Scope:
- Integration with existing `uploadToAppServices`
- Add success/error handling on the modal
- Update some static text
=> [DEVHUB-1381]: Sign Up Modal - GET/POST Data & Functionality

.dockerignore, environments/prod.yaml, environments/staging.yaml
Just doing a basic check here, I think that's all we really need. 
Also changed the .dockerignore file to ignore files we don't need in the containers.
=> [DEVHUB-1390] Add Prometheus

next.config.js
Copying this config from devcenter, because we're having some revalidation issues with the CDN so maybe this will help.
=> [CHORE] Add security and cache headers

data/statistics.json, src/components/content-preview/content-preview.tsx, src/components/course-header/course-header.tsx, src/components/social-share/social-share.spec.tsx, src/components/social-share/social-share.tsx
…es (#47)
* random changes
* fix failing test
=> Minor updates for UAT

data/student-resources.json, src/components/form/styles.ts, src/components/student-resources/student-resources.tsx, src/lib/registration.ts
[DEVHUB-1450]: UAT: Update student benefits description
[DEVHUB-1451]: UAT: update the Join Educator Community form
[DEVHUB-1452]: UAT: update Join Educator Community form
=> [DEVHUB-1450], [DEVHUB-1451], [DEVHUB-1452]

src/components/featured-card/featured-card.tsx, src/components/featured-card/styles.ts
* ux fixes for featured card
* code cleanup
=> 2022-08-15 Release

src/lib/airtable.ts, src/lib/app-services.ts
[DEVHUB-1466](https://jira.mongodb.org/browse/DEVHUB-1466)
The main issue was on the Airtable side, but I've added some sentry logging so we know when things go wrong in the future.
=> [DEVHUB-1466] Add sentry logging to registration uploads

environments/prod.yaml, src/lib/airtable.ts, src/lib/db.ts, src/lib/ses.ts, src/pages/api/registration.ts
[DEVHUB-1455](https://jira.mongodb.org/browse/DEVHUB-1455)
=> [DEVHUB-1455] Implement SES, add submit_date to db registrations

package.json, src/components/card/card.tsx, src/components/content-preview/content-preview.tsx, src/components/course-aside/course-aside.tsx, src/components/course-header/course-header.tsx, src/components/course-list/course-list.tsx, src/components/featured-card/featured-card.tsx, src/components/form/form.tsx, src/components/hero/hero.tsx, src/components/statistic/statistic.tsx, src/components/student-resources/student-resources.tsx, src/pages/courses/[course].tsx, yarn.lock
Closes - https://jira.mongodb.org/browse/DEVHUB-1423
=> [DEVHUB-1423]: Upgrade Flora Version for React 18 Type Support

package.json, src/components/card/card.tsx, src/components/content-preview/content-preview.tsx, src/components/course-aside/course-aside.tsx, src/components/course-header/course-header.tsx, src/components/course-list/course-list.tsx, src/components/featured-card/featured-card.tsx, src/components/form/form.tsx, src/components/hero/hero.tsx, src/components/statistic/statistic.tsx, src/components/student-resources/student-resources.tsx, src/pages/courses/[course].tsx, yarn.lock
* upgrade flora, remove ts-ignore statements
* flora minor version bump
=> [DEVHUB-1423]: Upgrade Flora Version for React 18 Type Support (#81)

package.json, yarn.lock
Updated consistent nav version to 1.2.27
=> [DEVHUB-1679] Consistent Nav Version update 1.2.27

data/FAQs/faq-promotional-code.md, src/components/program-benefits/program-benefits.tsx, src/components/program-benefits/styles.ts
Ticket: https://jira.mongodb.org/browse/LRN-340
=> [LRN-340]: UX Feedback and Content Updates

jest.config.js, src/components/course-aside/course-aside.tsx, src/components/layout.tsx, src/components/modal/educator-verification/educator-verification.tsx, src/components/modal/educator-verification/index.ts, src/components/modal/educator-verification/sheer-id-container.tsx, src/components/modal/educator-verification/styles.ts, src/components/modal/educator-verification/utils.ts, src/components/modal/index.ts, src/components/modal/modal.tsx, src/components/modal/styles.ts, src/contexts/modal.tsx, src/hooks/useOnClickOutside.tsx, src/pages/_app.tsx, src/pages/_document.tsx, src/pages/index.tsx, tsconfig.json
Ticket: https://jira.mongodb.org/browse/LRN-339
=> [LRN-339]: Frontend Development - Implement Modal User Flow

src/components/form/custom-fields/course-syllabus.tsx, src/components/form/custom-fields/styles.ts, src/components/form/form.spec.tsx, src/components/form/form.tsx
Ticket from testing: https://jira.mongodb.org/browse/LRN-396
=> [UAT]: Make Course Syllabus Field Mandatory

data/hero.json, data/statistics.json, data/student-resources.json, src/components/student-resources/student-resources.tsx, src/components/student-resources/styles.ts
Ticket: https://jira.mongodb.org/browse/UP-5878
=> [UP-5878]: Copy Updates for /academia

src/pages/_app.tsx
Ticket: https://jira.mongodb.org/browse/UP-5883
Note: this ticket satisfies the ask to add SEO-related `<link />` and `<meta />` tags to Academia page. The addition to sitemap-index will have to occur in the DevCenter repo in a separate PR.
=> [UP-5883]: SEO for https://www.mongodb.com/academia

src/components/form/utils.ts, src/pages/api/phd-fellowship/application.ts
Link To Ticket: https://jira.mongodb.org/browse/UP-6034
=> [Up-6034]: Add Country field to Form

src/pages/phd-fellowship.tsx, src/styles/phd-fellowship.ts
Tickets:
- https://jira.mongodb.org/browse/UP-6056
- https://jira.mongodb.org/browse/UP-6057
- https://jira.mongodb.org/browse/UP-6058
=> [UP-6056], [UP-6057], [UP-6058]: SEO UAT Feedback

src/pages/_app.tsx, src/pages/courses/[course].tsx, src/pages/index.tsx
Ticket: https://jira.mongodb.org/browse/UP-6056
=> [UP-6056]: Update Canonical to be Self Referencing

data/FAQs/phd-fellowship/research.md, src/pages/_app.tsx, src/pages/courses/[course].tsx, src/pages/index.tsx, src/pages/phd-fellowship.tsx
Ticket: https://jira.mongodb.org/browse/UP-6059
=> [UP-6059]: Editing PhD Fellowship Page

data/statistics.json
[DEVHUB-1716](https://jira.mongodb.org/browse/DEVHUB-1716)
=> [DEVHUB-1716] Update number of companies using MongoDB

package.json, src/components/content-preview/content-preview.tsx, src/components/course-header/course-header.tsx, src/components/course-list/course-list.tsx, src/lib/apollo-client.ts, src/lib/cms-content.ts, yarn.lock
[DEVHUB-1823](https://jira.mongodb.org/browse/DEVHUB-1823)
=> [DEVHUB-1823] Add Apollo and consume ContentStack data

data/FAQs/educators-program/fellowship.md, data/FAQs/educators-program/index.ts, src/components/form/form.tsx, src/components/form/types.ts, src/pages/_app.tsx, src/pages/phd-fellowship.tsx
Tickets:
https://jira.mongodb.org/browse/UP-6077
https://jira.mongodb.org/browse/UP-6081
=> [UP-6077] & [UP-6081]: PhD Fellowship Page Updates

package.json, yarn.lock
Per the web team we need this deployed today.
=> Bump consistent nav to 1.2.39

src/pages/api/phd-fellowship/application.ts
[DEVHUB-1916](https://jira.mongodb.org/browse/DEVHUB-1916)
=> [DEVHUB-1916] Add Acceptance Criteria table, adjust tables

sentry.properties, src/pages/api/phd-fellowship/application.ts
Got new token for Jira to upload to the ACADEMIA project, and changing sentry org because we need to.
=> [FIX] Change Sentry org, change Jira Project

package.json, yarn.lock
Will update when they release the official 2.0 version.
=> Update Consistent Nav to 2.0

package.json, src/pages/api/educator-program/registration.ts, src/pages/api/phd-fellowship/application.ts, src/pages/api/revalidate.ts, yarn.lock
https://jira.mongodb.org/browse/UP-6354
=> [UP-6354] Upgrade Sentry to Latest Version

package.json, yarn.lock
=> [CONSISTENT NAV] Bump nav again.
